### ISSUE TITLE
Interface for windows?

### ISSUE THREAD

**Issue by SanthoshDhandapani** [wankdanker/node-write-file-queue#1]
From your example i noticed that interface /dev/usb/lp0 works fine with linux, could you please share the similar interface for windows.

**Comment by wankdanker** [comment]
Unfortunately I do not know the answer to that question. After some quick research, I found these pages that might provide an answer. I unfortunately do not have the time at the moment to test and find out what works. If you find out what works, please report back.

* https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx
* https://en.wikipedia.org/wiki/Device_file#DOS.2C_TOS.2C_OS.2F2.2C_and_Windows

**Comment by SanthoshDhandapani** [comment]
Thanks for your quick response, definitely I will update here if any thing works.

**Comment by SanthoshDhandapani** [comment]
After a lot of research atlast i found a working solution.
For Windows:
1) Install corresponding printer driver
2) Enable share printer and give a share name from printer properties by right clicking on the printer
3) Now input the interface in printer config as shown below
Syntax: \\\\HOST_NAME\\SHARED_PRINTER_NAME
Example: \\\\192.168.2.20\\Posiflex
 (OR) \\\\MY-PC\\Posiflex
